import React, { useState, useRef, useEffect } from 'react';
import { useTOC } from '@docusaurus/theme-common/internal';
import styles from './RAGChatbot.module.css';

const RAGChatbot = () => {
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!inputValue.trim() || isLoading) return;

    // Add user message
    const userMessage = { id: Date.now(), text: inputValue, sender: 'user' };
    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);

    try {
      // In a real implementation, this would call the backend RAG API
      // For now, we'll simulate a response
      const response = await simulateRAGResponse(inputValue);

      const botMessage = {
        id: Date.now() + 1,
        text: response.text,
        sender: 'bot',
        citations: response.citations,
        confidence: response.confidence
      };

      setMessages(prev => [...prev, botMessage]);
    } catch (error) {
      const errorMessage = {
        id: Date.now() + 1,
        text: 'Sorry, I encountered an error processing your request. Please try again.',
        sender: 'bot',
        isError: true
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  // Simulate RAG response - in real implementation, this would call the backend API
  const simulateRAGResponse = async (query) => {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1000));

    // This is a placeholder - in real implementation, this would call the actual RAG API
    return {
      text: `This is a simulated response to your query: "${query}". In the real implementation, this would be generated by the RAG system using textbook content with proper citations and confidence scores.`,
      citations: [
        { source: 'ROS2 Module, Chapter 1', page: 'ros2/chapter-1', confidence: 0.92 },
        { source: 'Isaac Module, Chapter 2', page: 'isaac/chapter-2', confidence: 0.87 }
      ],
      confidence: 0.89
    };
  };

  const handleSelectedText = async () => {
    const selectedText = window.getSelection().toString().trim();
    if (selectedText) {
      // Add user query about selected text
      const queryMessage = {
        id: Date.now(),
        text: `About this text: "${selectedText}"`,
        sender: 'user'
      };
      setMessages(prev => [...prev, queryMessage]);
      setIsLoading(true);

      try {
        const response = await simulateRAGResponse(`Explain this text: ${selectedText}`);
        const botMessage = {
          id: Date.now() + 1,
          text: response.text,
          sender: 'bot',
          citations: response.citations,
          confidence: response.confidence
        };
        setMessages(prev => [...prev, botMessage]);
      } catch (error) {
        const errorMessage = {
          id: Date.now() + 1,
          text: 'Sorry, I encountered an error processing your request. Please try again.',
          sender: 'bot',
          isError: true
        };
        setMessages(prev => [...prev, errorMessage]);
      } finally {
        setIsLoading(false);
      }
    }
  };

  // Add event listener for text selection
  useEffect(() => {
    const handleMouseUp = () => {
      const selectedText = window.getSelection().toString().trim();
      if (selectedText.length > 10) { // Only show for meaningful selections
        // You could show a floating button or tooltip here
        console.log('Selected text:', selectedText);
      }
    };

    document.addEventListener('mouseup', handleMouseUp);
    return () => document.removeEventListener('mouseup', handleMouseUp);
  }, []);

  return (
    <div className={styles.chatbotContainer}>
      <div className={styles.chatHeader}>
        <h3>Textbook RAG Chatbot</h3>
        <p>Ask questions about the textbook content. Responses are based on book-only information with citations.</p>
      </div>

      <div className={styles.chatMessages}>
        {messages.length === 0 ? (
          <div className={styles.welcomeMessage}>
            <p>Hello! I'm your textbook assistant. Ask me questions about Physical AI and Humanoid Robotics, and I'll provide answers based on the textbook content with proper citations.</p>
            <p>Try asking about ROS2 concepts, Isaac Sim, or VLA models!</p>
          </div>
        ) : (
          messages.map((message) => (
            <div
              key={message.id}
              className={`${styles.message} ${
                message.sender === 'user' ? styles.userMessage : styles.botMessage
              }`}
            >
              <div className={styles.messageContent}>
                <p>{message.text}</p>
                {message.citations && message.citations.length > 0 && (
                  <div className={styles.citations}>
                    <strong>Citations:</strong>
                    <ul>
                      {message.citations.map((citation, idx) => (
                        <li key={idx}>
                          <a href={`/${citation.page}`} target="_blank" rel="noopener noreferrer">
                            {citation.source} (Confidence: {(citation.confidence * 100).toFixed(1)}%)
                          </a>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {message.confidence && !message.citations && (
                  <div className={styles.confidence}>
                    Confidence: {(message.confidence * 100).toFixed(1)}%
                  </div>
                )}
                {message.isError && (
                  <div className={styles.error}>
                    ⚠️ An error occurred. Please try again.
                  </div>
                )}
              </div>
            </div>
          ))
        )}
        {isLoading && (
          <div className={styles.message + ' ' + styles.botMessage}>
            <div className={styles.messageContent}>
              <div className={styles.typingIndicator}>
                <div></div>
                <div></div>
                <div></div>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <form onSubmit={handleSubmit} className={styles.chatInputForm}>
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="Ask a question about the textbook content..."
          disabled={isLoading}
          className={styles.chatInput}
        />
        <button type="submit" disabled={isLoading || !inputValue.trim()} className={styles.sendButton}>
          {isLoading ? 'Sending...' : 'Send'}
        </button>
      </form>

      <div className={styles.chatFooter}>
        <p><strong>Note:</strong> This chatbot provides book-only answers with citations and confidence scores, responding in under 800ms.</p>
      </div>
    </div>
  );
};

export default RAGChatbot;